routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Farm\FarmController;
use App\Http\Controllers\Farm\PackageController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\User\Admin\AdminController as TheAdminController;
use App\Http\Controllers\User\Referral\ReferralController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Http\Controllers\Transaction\InvestmentController;
use App\Http\Controllers\Transaction\MandateController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\Admin\RoleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('/dashboard');
});

Route::group(['middleware'=>'is_admin'], function(){
	Route::get('/', [AdminController::class, '__invoke']);
	Route::get('/dashboard', [AdminController::class, '__invoke'])->name('admin.dashboard');
	Route::resource('farmlists', FarmController::class);
	Route::resource('packages', PackageController::class);
	Route::resource('users', UserController::class);
	Route::resource('referrals', ReferralController::class)->only(['index']);
	Route::resource('transactions', TransactionController::class)->only(['index']);
	Route::resource('mandates', MandateController::class)->only(['index', 'destroy', 'edit', 'update']);
	Route::resource('investments', InvestmentController::class)->only(['index']);
	Route::resource('settings', SettingController::class)->only(['index', 'edit', 'update']);
	Route::resource('roles', RoleController::class);
	Route::resource('administrators', TheAdminController::class);
	Route::get('/transactions/{id}/{action}', [TransactionController::class, 'changeStatus']);
	Route::get('/users/{id}/perm', [UserController::class, 'perm']);
	Route::get('/farmlists/{slug}/create', [FarmController::class, 'addToPackage']);
	Route::get('/investments/{id}/{action}', [InvestmentController::class, 'changeStatus']);
	Route::get('/notifications', function(){
		return view('notifications.admin.index');
	});
	Route::get('/notifications/{id}', function($id){
		DB::table('notifications')->where('id', $id)->update(['read_at'=>\Carbon\Carbon::now()]);
		$notification = DB::table('notifications')->where('id', $id)->first();
		return view('notifications.admin.show', ['id'=>$id, 'notification'=>$notification]);
	});
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\DashboardController;
use App\Http\Controllers\Farm\FarmController;
use App\Http\Controllers\Farm\PackageController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\Transaction\CardController;
use App\Http\Controllers\Transaction\BankController;
use App\Http\Controllers\Transaction\InvestmentController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Http\Controllers\User\Referral\ReferralController;
use App\Http\Controllers\User\WalletController;
use App\Http\Controllers\NotificationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/dashboard');
});

Route::get('/verify_referree/{referree}', [UserController::class, 'verifyReferree'])->name('verify_referee');

Route::group(['middleware'=>['auth:sanctum', 'verified', 'is_user']], function(){
	Route::group(['middleware'=>'is_complete'], function(){
		Route::get('/dashboard', [DashboardController::class, '__invoke'])->name('dashboard');
		Route::resource('farms', FarmController::class)->only(['show']);
		Route::get('/farms/{id}/invest', [FarmController::class, 'invest']);
		Route::resource('packages', PackageController::class)->only(['index']);
		Route::resource('investments', InvestmentController::class)->except(['destroy', 'edit', 'update']);
		Route::resource('transactions', TransactionController::class)->only(['index']);
		Route::resource('referrals', ReferralController::class)->only(['index']);
		Route::get('/add-funds', [WalletController::class, 'addFunds']);
		Route::post('/add-funds', [WalletController::class, 'addFundPost'])->name('wallet.addFunds');
		Route::get('/withdraw-fund', [WalletController::class, 'withdrawFunds']);
		Route::post('/withdraw-fund', [WalletController::class, 'withdrawFundPost'])->name('wallet.withdrawFunds');
		Route::get('/notifications', function(){
			return view('notifications.index');
		});
		Route::get('/notifications/{id}', function($id){
			DB::table('notifications')->where('id', $id)->update(['read_at'=>\Carbon\Carbon::now()]);
			$notification = DB::table('notifications')->where('id', $id)->first();
			return view('notifications.show', ['id'=>$id, 'notification'=>$notification]);
		});
	});
	Route::get('/profile', [UserController::class, 'profile']);
	Route::put('/profile/update/{id}', [UserController::class, 'update'])->name('profile.update');
	Route::resource('cards', CardController::class)->only(['destroy']);
	Route::resource('banks', BankController::class)->only(['store', 'destroy', 'update']);
	Route::get('/card/add', [CardController::class, 'addCard']);
	Route::get('/verifyPayment', [CardController::class, 'verifyPayment'])->name('card.process');
	Route::get('/verifyPayment/invest', [InvestmentController::class, 'verifyPayment'])->name('card.process.invest');
});
Route::get('/verify_referee/{ref}', [UserController::class, 'verify_referee'])->name('verify.referee');
Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
    return redirect('/dashboard');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();
    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

resources/views/admins/create.blade.php
@extends('layouts.admin')

@section('title', __('Add a new administrator'))

@section('bread')
<div class="page-title-box">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <h4 class="page-title">Administrators</h4>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item"><a href="/">City Fresh Farms</a></li>
                <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="/administrators">Administrators</a></li>
                <li class="breadcrumb-item active">Add new user</li>
            </ol>
        </div>
    </div>
</div>
@endsection

@push('more-styles')
@endpush

@push('more-scripts')
@endpush

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card m-b-30">
            <div class="card-body">
                <h4 class="mt-0 header-title">Add new user</h4>
                <p class="sub-title"></p>
                <form action="{{ route('administrators.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="form-group col-4">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" required>
                        </div>
                        <div class="form-group col-4">
                            <label>E-mail</label>
                            <input type="email" name="email" class="form-control" required>
                            @error('email')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>Phone</label>
                            <input class="form-control" type="number" name="phone" required>
                            @error('phone')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>Roles</label>
                            <select class="form-control" name="roles[]" multiple>
                                @foreach($roles as $role)
                                <option value="{{ $role->id }}">{{ $role->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-12">
                            <button class="btn btn-primary btn-lg" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admins/edit.blade.php
@extends('layouts.admin')

@section('title', __('Edit administrator'))

@section('bread')
<div class="page-title-box">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <h4 class="page-title">Administrators</h4>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item"><a href="/">City Fresh Farms</a></li>
                <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="/administrators">Administrators</a></li>
                <li class="breadcrumb-item active">Edit user</li>
            </ol>
        </div>
    </div>
</div>
@endsection

@push('more-styles')
@endpush

@push('more-scripts')
@endpush

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card m-b-30">
            <div class="card-body">
                <h4 class="mt-0 header-title">Edit user</h4>
                <p class="sub-title"></p>
                <form action="{{ route('administrators.update', $entity->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="form-group col-4">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" required value="{{ $entity->name }}">
                        </div>
                        <div class="form-group col-4">
                            <label>E-mail</label>
                            <input type="email" name="email" class="form-control" readonly value="{{ $entity->email }}">
                        </div>
                        <div class="form-group col-4">
                            <label>Phone</label>
                            <input class="form-control" type="number" name="phone" readonly value="{{ $entity->phone }}">
                        </div>
                        <div class="form-group col-4">
                            <label>Roles</label>
                            <select class="form-control" name="roles[]" multiple>
                                @foreach($roles as $role)
                                <option value="{{ $role->id }}" {{ $entity->roles()->where('id', $role->id)->first() ? 'selected' : '' }}>{{ $role->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-12">
                            <button class="btn btn-primary btn-lg" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admins/index.blade.php
@extends('layouts.admin')

@section('title', __('All Administrators'))

@section('bread')
<div class="page-title-box">
	<div class="row align-items-center">
		<div class="col-sm-6">
			<h4 class="page-title">Users</h4>
		</div>
		<div class="col-sm-6">
			<ol class="breadcrumb float-right">
				<li class="breadcrumb-item"><a href="/">City Fresh Farms</a></li>
				<li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
				<li class="breadcrumb-item active">Administrators</li>
			</ol>
		</div>
	</div>
</div>
@endsection

@push('more-styles')
<link href="{{ asset('plugins/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('plugins/datatables/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
@endpush

@push('more-scripts')
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/jszip.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/pages/datatables.init.js') }}"></script>
<script>
    $(function(){
        $('.permAction').click(function(e){
            e.preventDefault();
            var link = $(this).attr('href');
            Swal.fire({
                title: 'Are you sure?',
                text: "This might affect how the user accesses the platform!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, proceed!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger ml-2',
                buttonsStyling: false
            }).then((result) => {
                if(result.isConfirmed){
                    window.location.href = link;
                }
            });
        });
    });
</script>
@endpush

@section('content')
<div class="row">
	<div class="col-12">
		<div class="card m-b-30">
			<div class="card-body">
				<h4 class="mt-0 header-title">All Users</h4>
				<p class="sub-title">
				</p>
				<table id="datatable" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
					<thead>
						<tr>
							<th>#</th>
							<th>Name</th>
							<th>E-mail</th>
							<th>Phone</th>
							<th>Status</th>
							<th>Date Created</th>
							<th><a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown">Action </a></th>
						</tr>
					</thead>
					<tbody>
						@foreach($entities as $entity)
						<tr>
							<td>{{ $loop->iteration }}</td>
							<td>{{ $entity->name() }}</td>
							<td>{{ $entity->email }}</td>
							<td>{{ $entity->phone }}</td>
							<td>{!! $entity->status() !!}</td>
							<td>{{ date('d M, Y h:i A', strtotime($entity->created_at)) }}</td>
							<td>
								<div class="drodown">
									<a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><i class="text-primary ti-more-alt"></i></a>
									<ul class="dropdown-menu dropdown-menu-right">
										<li class="dropdown-item"><a href="/administrators/{{ $entity->id }}"><span>View Admin</span></a></li>
										<li class="dropdown-item"><a href="/administrators/{{ $entity->id }}/edit"><span>Edit Admin</span></a></li>
										<li class="dropdown-item"><a href="/users/{{ $entity->id }}/perm" class="permAction"><span>{{ $entity->is_active ? 'Restrict User' : 'Unrestrict User' }}</span></a></li>
									</ul>
								</div>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<!-- end col -->
</div>
<!-- end row -->
@endsection

resources/views/admins/show.blade.php
@extends('layouts.admin')

@section('title', __('View Admin Details'))

@push('more-styles')
<link href="{{ asset('plugins/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('plugins/datatables/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
@endpush


@push('more-scripts')
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/jszip.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/pages/datatables.init.js') }}"></script>
<script>
    $(function(){
        $('.deleteAction').click(function(e){
            e.preventDefault();
            var form = $(this).attr('data-target');
            Swal.fire({
                title: 'Are you sure?',
                text: "This action cannot be reverted!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger ml-2',
                buttonsStyling: false
            }).then((result) => {
                if(result.isConfirmed){
                    $(form).submit();
                }
            });
        });
        $('.permAction').click(function(e){
            e.preventDefault();
            var link = $(this).attr('href');
            Swal.fire({
                title: 'Are you sure?',
                text: "This might affect how the user accesses the platform!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, proceed!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger ml-2',
                buttonsStyling: false
            }).then((result) => {
                if(result.isConfirmed){
                    window.location.href = link;
                }
            });
        });
        $('.datatable').dataTable();
    });
</script>
@endpush

@section('bread')
<div class="page-title-box">
	<div class="row align-items-center">
		<div class="col-sm-6">
			<h4 class="page-title">Viewing Administrators</h4>
		</div>
		<div class="col-sm-6">
			<ol class="breadcrumb float-right">
				<li class="breadcrumb-item"><a href="/">City Fresh Farms</a></li>
				<li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
				<li class="breadcrumb-item"><a href="/administrators">Administrators</a></li>
				<li class="breadcrumb-item active">View</li>
			</ol>
		</div>
	</div>
</div>
@endsection

@section('content')
<div class="row">
	<div class="col-lg-4">
		<div class="card m-b-30">
			<div class="card-body">
				<h4 class="mt-0 header-title">{{ $entity->id() }}</h4>
				<div class="">
					<div class="table-responsive">
                        <table class="table mb-0">
                            <thead>
                                <tr>
                                    <th>Entry</th>
                                    <th>Value</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><strong>Name</strong></td>
                                    <td>{{ $entity->name() }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Status</strong></td>
                                    <td>{!! $entity->status() !!}</td>
                                </tr>
                                <tr>
                                    <td><strong>Email</strong></td>
                                    <td>{{ $entity->email }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Phone</strong></td>
                                    <td>{{ $entity->phone }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Date Added</strong></td>
                                    <td>{{ date('d M, Y h:i A', strtotime($entity->created_at))}}</td>
                                </tr>
                                <tr>
                                    <td><strong>Date Last Updated</strong></td>
                                    <td>{{ date('d M, Y h:i A', strtotime($entity->created_at))}}</td>
                                </tr>
                                <tr>
                                    <td><strong>Roles</strong></td>
                                    <td>
                                    	@foreach($entity->roles as $role)
                                    	<a href="/roles/{{ $role->id }}" target="_blank"> {{ $role->name }} <i class="mdi mdi-link"></i></a><br>
                                    	@endforeach
                                    </td>
                                </tr>
                                <tr>
                                	<td></td>
                                	<td></td>
                                </tr>
                                <tr>
                                    <td><strong>Total Packages Created</strong></td>
                                    <td>
                                    	{{ $entity->packages()->count() }}
                                    </td>
                                </tr>
                                <tr>
                                    <td><strong>Total Farms Created</strong></td>
                                    <td>
                                    	{{ $entity->farms()->count() }}
                                    </td>
                                </tr>
                                <tr>
                                    <td><strong>Pending Farms Created</strong></td>
                                    <td>
                                    	{{ $entity->farms()->where('status', 'pending')->count() }}
                                    </td>
                                </tr>
                                <tr>
                                    <td><strong>Closed Farms Created</strong></td>
                                    <td>
                                    	{{ $entity->farms()->where('status', 'closed')->count() }}
                                    </td>
                                </tr>
                                <tr>
                                    <td><strong>Pending Farms Created</strong></td>
                                    <td>
                                    	{{ $entity->farms()->where('status', 'pending')->count() }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-12"><a href="/users/{{ $entity->id }}/perm" class="permAction btn btn-danger btn-lg">{{ $entity->is_active ? 'Restrict User' : 'Unrestrict User' }}</a> <a href="/users/{{ $entity->id }}/edit" class="btn btn-warning btn-lg ml-2">Edit Account</a></div>
                    </div>
				</div>
			</div>
		</div>
	</div>
    <div class="col-xl-8">
        <div class="card m-b-30">
            <div class="card-body">
                <h4 class="mt-0 header-title">All Packages</h4>
                <p class="sub-title">
                </p>
                <table class="datatable table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
					<thead>
						<tr>
							<th>#</th>
							<th>Name</th>
							<th>Farms</th>
							<th>Created by</th>
							<th>Created at</th>
							<th><a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown">Action </a></th>
						</tr>
					</thead>
					<tbody>
						@foreach($entity->packages as $package)
						<tr>
							<td>{{ $loop->iteration }}</td>
							<td>{{ $package->name }}</td>
							<td>{{ $package->farms()->count() }}</td>
							<td>{{ $package->user->name }}</td>
							<td>{{ date('d M, Y h:i A', strtotime($package->created_at)) }}</td>
							<td>
								<div class="drodown">
									<a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><i class="text-primary ti-more-alt"></i></a>
									<ul class="dropdown-menu dropdown-menu-right">
										<li class="dropdown-item"><a href="/packages/{{ $package->slug }}"><span>View Package</span></a></li>
										<li class="dropdown-item"><a href="/packages/{{ $package->slug }}/edit"><span>Edit Package</span></a></li>
										<li class="dropdown-item"><a href="/farmlists/{{ $package->slug }}/create"><span>Add Farm</span></a></li>
										<li class="dropdown-item"><a href="" class="deleteAction" data-target="#delete-package{{$package->id}}"><span>Remove Package</span></a></li>
                                        <form id="delete-package{{$package->id}}" action="{{ route('packages.destroy', $package->id) }}" method="POST" class="d-none">
                                            @csrf
                                            @method('DELETE')
                                        </form>
									</ul>
								</div>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
            </div>
        </div>
        <div class="card m-b-30 mt-3">
            <div class="card-body">
                <h4 class="mt-0 header-title">All Farms</h4>
                <p class="sub-title">
                </p>
                <table class="datatable table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
					<thead>
						<tr>
							<th>#</th>
							<th>Name</th>
							<th>Cover Image</th>
							<th>Start date</th>
							<th>Close date</th>
							<th>Duration</th>
							<th>Package</th>
							<th>Status</th>
							<th><a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown">Action </a></th>
						</tr>
					</thead>
					<tbody>
						@foreach($entity->farms as $farm)
						<tr>
							<td>{{ $loop->iteration }}</td>
							<td>{{ $farm->name }}</td>
							<td><img src="{{ $farm->cover_image }}" width="120px"></td>
							<td>{{ date('d M, Y h:i A', strtotime($farm->start_date)) }}</td>
							<td>{{ date('d M, Y h:i A', strtotime($farm->close_date)) }}</td>
							<td>{{ $farm->duration }} {{ $farm->duration_type }}</td>
							<td><a href="/packages/{{ $farm->package->slug }}" class="text text-primary" target="_blank">{{ $farm->package->name }} <i class="mdi mdi-link"></i></a></td>
							<td>{!! $farm->status() !!}</td>
							<td>
								<div class="drodown">
									<a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><i class="text-primary ti-more-alt"></i></a>
									<ul class="dropdown-menu dropdown-menu-right">
										<li class="dropdown-item"><a href="/farmlists/{{ $farm->slug }}"><span>View Farm</span></a></li>
										@if($farm->status == 'pending')
										<li class="dropdown-item"><a href="/farmlists/{{ $farm->slug }}/edit"><span>Edit Farm</span></a></li>
										@endif
										<li class="dropdown-item"><a href="" class="deleteAction" data-target="#delete-farm{{$farm->id}}"><span>Remove Farm</span></a></li>
                                        <form id="delete-farm{{$farm->id}}" action="{{ route('farmlists.destroy', $farm->id) }}" method="POST" class="d-none">
                                            @csrf
                                            @method('DELETE')
                                        </form>
									</ul>
								</div>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
            </div>
        </div>
    </div>
</div>
@endsection