routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Farm\FarmController;
use App\Http\Controllers\Farm\PackageController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\User\Admin\AdminController as TheAdminController;
use App\Http\Controllers\User\Referral\ReferralController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Http\Controllers\Transaction\InvestmentController;
use App\Http\Controllers\Transaction\MandateController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\Admin\RoleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('/dashboard');
});

Route::group(['middleware'=>'is_admin'], function(){
	Route::get('/', [AdminController::class, '__invoke']);
	Route::get('/dashboard', [AdminController::class, '__invoke'])->name('admin.dashboard');
	Route::resource('farmlists', FarmController::class);
	Route::resource('packages', PackageController::class);
	Route::resource('users', UserController::class);
	Route::resource('referrals', ReferralController::class)->only(['index']);
	Route::resource('transactions', TransactionController::class)->only(['index']);
	Route::resource('mandates', MandateController::class)->only(['index', 'destroy', 'edit', 'update']);
	Route::resource('investments', InvestmentController::class)->only(['index']);
	Route::resource('settings', SettingController::class)->only(['index', 'edit', 'update']);
	Route::resource('roles', RoleController::class);
	Route::resource('administrators', TheAdminController::class);
	Route::get('/transactions/{id}/{action}', [TransactionController::class, 'changeStatus']);
	Route::get('/users/{id}/perm', [UserController::class, 'perm']);
	Route::get('/farmlists/{slug}/create', [FarmController::class, 'addToPackage']);
	Route::get('/investments/{id}/{action}', [InvestmentController::class, 'changeStatus']);
	Route::get('/notifications', function(){
		return view('notifications.admin.index');
	});
	Route::get('/notifications/{id}', function($id){
		DB::table('notifications')->where('id', $id)->update(['read_at'=>\Carbon\Carbon::now()]);
		$notification = DB::table('notifications')->where('id', $id)->first();
		return view('notifications.admin.show', ['id'=>$id, 'notification'=>$notification]);
	});
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\DashboardController;
use App\Http\Controllers\Farm\FarmController;
use App\Http\Controllers\Farm\PackageController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\Transaction\CardController;
use App\Http\Controllers\Transaction\BankController;
use App\Http\Controllers\Transaction\InvestmentController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Http\Controllers\User\Referral\ReferralController;
use App\Http\Controllers\User\WalletController;
use App\Http\Controllers\NotificationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/dashboard');
});

Route::get('/verify_referree/{referree}', [UserController::class, 'verifyReferree'])->name('verify_referee');

Route::group(['middleware'=>['auth:sanctum', 'verified', 'is_user']], function(){
	Route::group(['middleware'=>'is_complete'], function(){
		Route::get('/dashboard', [DashboardController::class, '__invoke'])->name('dashboard');
		Route::resource('farms', FarmController::class)->only(['show']);
		Route::get('/farms/{id}/invest', [FarmController::class, 'invest']);
		Route::resource('packages', PackageController::class)->only(['index']);
		Route::resource('investments', InvestmentController::class)->except(['destroy', 'edit', 'update']);
		Route::resource('transactions', TransactionController::class)->only(['index']);
		Route::resource('referrals', ReferralController::class)->only(['index']);
		Route::get('/add-funds', [WalletController::class, 'addFunds']);
		Route::post('/add-funds', [WalletController::class, 'addFundPost'])->name('wallet.addFunds');
		Route::get('/withdraw-fund', [WalletController::class, 'withdrawFunds']);
		Route::post('/withdraw-fund', [WalletController::class, 'withdrawFundPost'])->name('wallet.withdrawFunds');
		Route::get('/notifications', function(){
			return view('notifications.index');
		});
		Route::get('/notifications/{id}', function($id){
			DB::table('notifications')->where('id', $id)->update(['read_at'=>\Carbon\Carbon::now()]);
			$notification = DB::table('notifications')->where('id', $id)->first();
			return view('notifications.show', ['id'=>$id, 'notification'=>$notification]);
		});
	});
	Route::get('/profile', [UserController::class, 'profile']);
	Route::put('/profile/update/{id}', [UserController::class, 'update'])->name('profile.update');
	Route::resource('cards', CardController::class)->only(['destroy']);
	Route::resource('banks', BankController::class)->only(['store', 'destroy', 'update']);
	Route::get('/card/add', [CardController::class, 'addCard']);
	Route::get('/verifyPayment', [CardController::class, 'verifyPayment'])->name('card.process');
	Route::get('/verifyPayment/invest', [InvestmentController::class, 'verifyPayment'])->name('card.process.invest');
});
Route::get('/verify_referee/{ref}', [UserController::class, 'verify_referee'])->name('verify.referee');
Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
    return redirect('/dashboard');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();
    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

app/Http/Controllers/Farm/FarmController.php
<?php

namespace App\Http\Controllers\Farm;

use App\Http\Requests\Farm\FarmRequest;
use App\Http\Resources\Farm\FarmResource;
use App\Interfaces\Farm\FarmInterface;
use Shamaseen\Repository\Generator\Utility\Controller;

/**
 * Class FarmController
 * @package App\Http\Controllers\Farm
 * @property-read FarmInterface $interface
 */
class FarmController extends Controller
{

    protected $routeIndex = 'farms';

    protected $pageTitle = 'Farm';
    protected $createRoute = 'farms.create';

    protected $viewIndex = 'farms.index';
    protected $viewCreate = 'farms.create';
    protected $viewEdit = 'farms.edit';
    protected $viewShow = 'farms.show';

    /**
     * FarmController constructor.
     * @param FarmInterface $interface
     * @param FarmRequest $request
     * @param FarmResource $resource
     */
    public function __construct(FarmInterface $interface, FarmRequest $request)
    {
        parent::__construct($interface, $request, new  FarmResource([]));
        $this->middleware('can:view farms', ['only' => ['index', 'show']]);
        $this->middleware('can:create farms', ['only' => ['create', 'store']]);
        $this->middleware('can:edit farms', ['only' => ['edit', 'update']]);
        $this->middleware('can:delete farms', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->interface->index();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->interface->create();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        return $this->interface->store();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return $this->interface->show($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return $this->interface->edit($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id)
    {
        return $this->interface->update($id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @throws \Exception
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        return $this->interface->destroy($id);
    }

    public function invest($id)
    {
        return $this->interface->invest($id);
    }

    public function addToPackage($slug)
    {
        return $this->interface->addToPackage($slug);
    }
}

app/Http/Controllers/Farm/PackageController.php
<?php

namespace App\Http\Controllers\Farm;

use App\Http\Requests\Farm\PackageRequest;
use App\Http\Resources\Farm\PackageResource;
use App\Interfaces\Farm\PackageInterface;
use Shamaseen\Repository\Generator\Utility\Controller;

/**
 * Class PackageController
 * @package App\Http\Controllers\Farm
 * @property-read PackageInterface $interface
 */
class PackageController extends Controller
{

    protected $routeIndex = 'packages';

    protected $pageTitle = 'Package';
    protected $createRoute = 'packages.create';

    protected $viewIndex = 'packages.index';
    protected $viewCreate = 'packages.create';
    protected $viewEdit = 'packages.edit';
    protected $viewShow = 'packages.show';

    /**
     * PackageController constructor.
     * @param PackageInterface $interface
     * @param PackageRequest $request
     * @param PackageResource $resource
     */
    public function __construct(PackageInterface $interface, PackageRequest $request)
    {
        parent::__construct($interface, $request, new  PackageResource([]));
        $this->middleware('can:view packages', ['only' => ['index', 'show']]);
        $this->middleware('can:create packages', ['only' => ['create', 'store']]);
        $this->middleware('can:edit packages', ['only' => ['edit', 'update']]);
        $this->middleware('can:delete packages', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->interface->index();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return parent::create();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        return $this->interface->store();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return $this->interface->show($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return $this->interface->edit($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id)
    {
        return $this->interface->update($id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @throws \Exception
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        return $this->interface->destroy($id);
    }
}

resources/views/farms/create.blade.php
@extends('layouts.admin')

@section('title', __('Add a new Farm'))

@section('bread')
<div class="page-title-box">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <h4 class="page-title">Farm Lists</h4>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item"><a href="/">City Fresh Farms</a></li>
                <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="/farmlists">Farm List</a></li>
                <li class="breadcrumb-item active">Create Farm</li>
            </ol>
        </div>
    </div>
</div>
@endsection

@push('more-styles')
@endpush

@push('more-scripts')
@endpush

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card m-b-30">
            <div class="card-body">
                <h4 class="mt-0 header-title">Add new farm</h4>
                <p class="sub-title">Please fill in the farm details below carefully.</p>
                <form action="{{ route('farmlists.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @isset($package)
                    <input type="hidden" name="package" class="form-control" value="{{ $package->id }}">
                    @else
                    <div class="row">
                        <div class="form-group col-4">
                            <label>Package</label>
                            <select class="form-control" name="package">
                                @foreach($packages as $package)
                                <option value="{{ $package->id }}">{{ $package->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    @endisset
                    <div class="row">
                        <div class="form-group col-4">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control">
                            @error('name')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>Cover Image</label>
                            <input type="file" name="cover_image" class="form-control">
                            @error('cover_image')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>Start Date</label>
                            <input class="form-control" type="datetime-local" value="{{ date('Y-m-d') }}T{{ date('H:i:s') }}" name="start_date">
                            @error('start_date')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>Close Date</label>
                            <input class="form-control" type="datetime-local" value="{{ date('Y-m-d') }}T{{ date('H:i:s') }}" name="close_date">
                            @error('close_date')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>Duration</label>
                            <input class="form-control" type="number" name="duration">
                            @error('duration')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>Duration Type</label>
                            <select class="form-control" name="duration_type">
                                <option>Day</option>
                                <option>Week</option>
                                <option>Month</option>
                                <option>Year</option>
                            </select>
                        </div>
                        <div class="form-group col-4">
                            <label>Price Per Unit</label>
                            <input class="form-control" type="number" name="price_per_unit" step="any">
                            @error('price_per_unit')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>ROI</label>
                            <input class="form-control" type="number" name="roi" step="any">
                            @error('roi')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>Total Units</label>
                            <input class="form-control" type="number" name="total_units">
                            @error('total_units')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-12">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="customCheck2" name="allow_rollover">
                                <label class="custom-control-label font-weight-normal" for="customCheck2">Enable Roll Over</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <button class="btn btn-primary btn-lg" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/farms/edit.blade.php
@extends('layouts.admin')

@section('title', __('Edit farm'))

@section('bread')
<div class="page-title-box">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <h4 class="page-title">Editing farm</h4>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item"><a href="/">City Fresh Farms</a></li>
                <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="/farmlists">Farm List</a></li>
                <li class="breadcrumb-item"><a href="/farmlists/{{ $entity->slug }}">{{ $entity->name }}</a></li>
                <li class="breadcrumb-item active">Edit Farm</li>
            </ol>
        </div>
    </div>
</div>
@endsection

@push('more-styles')
@endpush

@push('more-scripts')
@endpush

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card m-b-30">
            <div class="card-body">
                <h4 class="mt-0 header-title">Edit farm</h4>
                <p class="sub-title">Please fill in the farm details below carefully.</p>
                <form action="{{ route('farmlists.update', $entity->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="form-group col-4">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" value="{{ $entity->name }}" readonly>
                        </div>
                        <div class="form-group col-4">
                            <label>Cover Image</label>
                            <input type="file" name="cover_image" class="form-control">
                            @error('cover_image')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>Start Date</label>
                            <input class="form-control" type="datetime-local" value="{{ date('Y-m-d', strtotime($entity->start_date)) }}T{{ date('H:i:s', strtotime($entity->start_date)) }}" name="start_date">
                            @error('start_date')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>Close Date</label>
                            <input class="form-control" type="datetime-local" value="{{ date('Y-m-d', strtotime($entity->close_date)) }}T{{ date('H:i:s', strtotime($entity->close_date)) }}" name="close_date">
                            @error('close_date')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>Duration</label>
                            <input class="form-control" type="number" name="duration" value="{{ $entity->duration }}">
                            @error('duration')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>Duration Type</label>
                            <select class="form-control" name="duration_type">
                                <option {{ $entity->duration_type == 'Day' ? 'checked':'' }}>Day</option>
                                <option {{ $entity->duration_type == 'Week' ? 'checked':'' }}>Week</option>
                                <option {{ $entity->duration_type == 'Month' ? 'checked':'' }}>Month</option>
                                <option {{ $entity->duration_type == 'Year' ? 'checked':'' }}>Year</option>
                            </select>
                        </div>
                        <div class="form-group col-4">
                            <label>Price Per Unit</label>
                            <input class="form-control" type="number" name="price_per_unit" step="any" value="{{ $entity->price_per_unit }}">
                            @error('price_per_unit')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>ROI</label>
                            <input class="form-control" type="number" name="roi" step="any" value="{{ $entity->roi }}">
                            @error('roi')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group col-4">
                            <label>Total Units</label>
                            <input class="form-control" type="number" name="total_units" value="{{ $entity->total_units }}">
                            @error('total_units')
                                <span class="text-danger">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="col-12">
                            <button class="btn btn-primary btn-lg" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/farms/index.blade.php
@extends('layouts.admin')

@section('title', __('Farm Lists'))

@section('bread')
<div class="page-title-box">
	<div class="row align-items-center">
		<div class="col-sm-6">
			<h4 class="page-title">Farm Lists</h4>
		</div>
		<div class="col-sm-6">
			<ol class="breadcrumb float-right">
				<li class="breadcrumb-item"><a href="/">City Fresh Farms</a></li>
				<li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
				<li class="breadcrumb-item active">Farm List</li>
			</ol>
		</div>
	</div>
</div>
@endsection

@push('more-styles')
<link href="{{ asset('plugins/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('plugins/datatables/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
@endpush

@push('more-scripts')
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/jszip.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/pages/datatables.init.js') }}"></script>
<script>
    $(function(){
        $('.deleteAction').click(function(e){
            e.preventDefault();
            var form = $(this).attr('data-target');
            Swal.fire({
                title: 'Are you sure?',
                text: "You want to delete this farm, every investments attached to this farm and every transaction history of these investments from the system!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger ml-2',
                buttonsStyling: false
            }).then((result) => {
                if(result.isConfirmed){
                    $(form).submit();
                }
            });
        });
    });
</script>
@endpush

@section('content')
<div class="row">
	<div class="col-12">
		<div class="card m-b-30">
			<div class="card-body">
				<h4 class="mt-0 header-title">All Farms</h4>
				<p class="sub-title">
					The list of all site farm lists displays here!
				</p>
				<table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
					<thead>
						<tr>
							<th>#</th>
							<th>Name</th>
							<th>Start date</th>
							<th>Close date</th>
							<th>Duration</th>
							<th>Package</th>
							<th>Status</th>
							<th><a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown">Action </a></th>
						</tr>
					</thead>
					<tbody>
						@foreach($entities as $entity)
						<tr>
							<td>{{ $loop->iteration }}</td>
							<td>{{ $entity->name }}</td>
							<td>{{ date('d M, Y h:i A', strtotime($entity->start_date)) }}</td>
							<td>{{ date('d M, Y h:i A', strtotime($entity->close_date)) }}</td>
							<td>{{ $entity->duration }} {{ $entity->duration_type }}</td>
							<td><a href="/packages/{{ $entity->package->slug }}" class="text text-primary" target="_blank">{{ $entity->package->name }} <i class="mdi mdi-link"></i></a></td>
							<td>{!! $entity->status() !!}</td>
							<td>
								<div class="drodown">
									<a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><i class="text-primary ti-more-alt"></i></a>
									<ul class="dropdown-menu dropdown-menu-right">
										<li class="dropdown-item"><a href="/farmlists/{{ $entity->slug }}"><span>View Farm</span></a></li>
										@if($entity->status == 'pending')
										<li class="dropdown-item"><a href="/farmlists/{{ $entity->slug }}/edit"><span>Edit Farm</span></a></li>
										@endif
										<li class="dropdown-item"><a href="" class="deleteAction" data-target="#delete-farm{{$entity->id}}"><span>Remove Farm</span></a></li>
                                        <form id="delete-farm{{$entity->id}}" action="{{ route('farmlists.destroy', $entity->id) }}" method="POST" class="d-none">
                                            @csrf
                                            @method('DELETE')
                                        </form>
									</ul>
								</div>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<!-- end col -->
</div>
<!-- end row -->
@endsection