routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Farm\FarmController;
use App\Http\Controllers\Farm\PackageController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\User\Admin\AdminController as TheAdminController;
use App\Http\Controllers\User\Referral\ReferralController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Http\Controllers\Transaction\InvestmentController;
use App\Http\Controllers\Transaction\MandateController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\Admin\RoleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('/dashboard');
});

Route::group(['middleware'=>'is_admin'], function(){
	Route::get('/', [AdminController::class, '__invoke']);
	Route::get('/dashboard', [AdminController::class, '__invoke'])->name('admin.dashboard');
	Route::resource('farmlists', FarmController::class);
	Route::resource('packages', PackageController::class);
	Route::resource('users', UserController::class);
	Route::resource('referrals', ReferralController::class)->only(['index']);
	Route::resource('transactions', TransactionController::class)->only(['index']);
	Route::resource('mandates', MandateController::class)->only(['index', 'destroy', 'edit', 'update']);
	Route::resource('investments', InvestmentController::class)->only(['index']);
	Route::resource('settings', SettingController::class)->only(['index', 'edit', 'update']);
	Route::resource('roles', RoleController::class);
	Route::resource('administrators', TheAdminController::class);
	Route::get('/transactions/{id}/{action}', [TransactionController::class, 'changeStatus']);
	Route::get('/users/{id}/perm', [UserController::class, 'perm']);
	Route::get('/farmlists/{slug}/create', [FarmController::class, 'addToPackage']);
	Route::get('/investments/{id}/{action}', [InvestmentController::class, 'changeStatus']);
	Route::get('/notifications', function(){
		return view('notifications.admin.index');
	});
	Route::get('/notifications/{id}', function($id){
		DB::table('notifications')->where('id', $id)->update(['read_at'=>\Carbon\Carbon::now()]);
		$notification = DB::table('notifications')->where('id', $id)->first();
		return view('notifications.admin.show', ['id'=>$id, 'notification'=>$notification]);
	});
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\User\DashboardController;
use App\Http\Controllers\Farm\FarmController;
use App\Http\Controllers\Farm\PackageController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\Transaction\CardController;
use App\Http\Controllers\Transaction\BankController;
use App\Http\Controllers\Transaction\InvestmentController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Http\Controllers\User\Referral\ReferralController;
use App\Http\Controllers\User\WalletController;
use App\Http\Controllers\NotificationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/dashboard');
});

Route::get('/verify_referree/{referree}', [UserController::class, 'verifyReferree'])->name('verify_referee');

Route::group(['middleware'=>['auth:sanctum', 'verified', 'is_user']], function(){
	Route::group(['middleware'=>'is_complete'], function(){
		Route::get('/dashboard', [DashboardController::class, '__invoke'])->name('dashboard');
		Route::resource('farms', FarmController::class)->only(['show']);
		Route::get('/farms/{id}/invest', [FarmController::class, 'invest']);
		Route::resource('packages', PackageController::class)->only(['index']);
		Route::resource('investments', InvestmentController::class)->except(['destroy', 'edit', 'update']);
		Route::resource('transactions', TransactionController::class)->only(['index']);
		Route::resource('referrals', ReferralController::class)->only(['index']);
		Route::get('/add-funds', [WalletController::class, 'addFunds']);
		Route::post('/add-funds', [WalletController::class, 'addFundPost'])->name('wallet.addFunds');
		Route::get('/withdraw-fund', [WalletController::class, 'withdrawFunds']);
		Route::post('/withdraw-fund', [WalletController::class, 'withdrawFundPost'])->name('wallet.withdrawFunds');
		Route::get('/notifications', function(){
			return view('notifications.index');
		});
		Route::get('/notifications/{id}', function($id){
			DB::table('notifications')->where('id', $id)->update(['read_at'=>\Carbon\Carbon::now()]);
			$notification = DB::table('notifications')->where('id', $id)->first();
			return view('notifications.show', ['id'=>$id, 'notification'=>$notification]);
		});
	});
	Route::get('/profile', [UserController::class, 'profile']);
	Route::put('/profile/update/{id}', [UserController::class, 'update'])->name('profile.update');
	Route::resource('cards', CardController::class)->only(['destroy']);
	Route::resource('banks', BankController::class)->only(['store', 'destroy', 'update']);
	Route::get('/card/add', [CardController::class, 'addCard']);
	Route::get('/verifyPayment', [CardController::class, 'verifyPayment'])->name('card.process');
	Route::get('/verifyPayment/invest', [InvestmentController::class, 'verifyPayment'])->name('card.process.invest');
});
Route::get('/verify_referee/{ref}', [UserController::class, 'verify_referee'])->name('verify.referee');
Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
    return redirect('/dashboard');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();
    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SettingRequest;
use App\Http\Resources\SettingResource;
use App\Interfaces\SettingInterface;
use Shamaseen\Repository\Generator\Utility\Controller;

/**
 * Class SettingController
 * @package App\Http\Controllers
 * @property-read SettingInterface $interface
 */
class SettingController extends Controller
{

    protected $routeIndex = 'settings';

    protected $pageTitle = 'Setting';
    protected $createRoute = 'settings.create';

    protected $viewIndex = 'settings.index';
    protected $viewCreate = 'settings.create';
    protected $viewEdit = 'settings.edit';
    protected $viewShow = 'settings.show';

    /**
     * SettingController constructor.
     * @param SettingInterface $interface
     * @param SettingRequest $request
     * @param SettingResource $resource
     */
    public function __construct(SettingInterface $interface, SettingRequest $request)
    {
        parent::__construct($interface, $request, new  SettingResource([]));
        $this->middleware('can:view settings', ['only' => ['index', 'show']]);
        $this->middleware('can:edit settings', ['only' => ['edit', 'update']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return parent::index();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return parent::create();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        return parent::store();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return parent::show($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return parent::edit($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update($id)
    {
        return parent::update($id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @throws \Exception
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        return parent::destroy($id);
    }
}

resources/views/settings/edit.blade.php
@extends('layouts.admin')

@section('title', __('Update System settings'))

@section('bread')
<div class="page-title-box">
	<div class="row align-items-center">
		<div class="col-sm-6">
			<h4 class="page-title">Update Settings</h4>
		</div>
		<div class="col-sm-6">
			<ol class="breadcrumb float-right">
				<li class="breadcrumb-item"><a href="/">City Fresh Farms</a></li>
				<li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
				<li class="breadcrumb-item active">Settings</li>
			</ol>
		</div>
	</div>
</div>
@endsection

@section('content')
<div class="row">
	<div class="col-xl-6">
		<div class="card card-bordered m-b-30">
			<div class="card-body">
				<h4 class="mt-0 header-title">Update settings</h4>
				<p class="sub-title">
				</p>
				<form action="{{ route('settings.update', $entity->id) }}" class="gy-3" method="post">
					@csrf
					@method('PUT')
					<div class="row g-3 align-center">
						<div class="col-lg-5">
							<div class="form-group">
								<label class="form-label">{{ ucwords(str_replace('-', ' ', $entity->name)) }}</label>
							</div>
						</div>
						<div class="col-lg-7">
							<div class="form-group">
								<div class="form-control-wrap">
									<input type="text" class="form-control" required="" name="value" value="{{ $entity->value }}">
								</div>
							</div>
						</div>
					</div>
					<div class="row g-3">
						<div class="col-lg-7 offset-lg-5">
							<div class="form-group mt-2">
								<button type="submit" class="btn btn-lg btn-primary">Submit</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/settings/index.blade.php
@extends('layouts.admin')

@section('title', __('All settings'))

@section('bread')
<div class="page-title-box">
	<div class="row align-items-center">
		<div class="col-sm-6">
			<h4 class="page-title">System Settings</h4>
		</div>
		<div class="col-sm-6">
			<ol class="breadcrumb float-right">
				<li class="breadcrumb-item"><a href="/">City Fresh Farms</a></li>
				<li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
				<li class="breadcrumb-item active">Settings</li>
			</ol>
		</div>
	</div>
</div>
@endsection

@push('more-styles')
<link href="{{ asset('plugins/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('plugins/datatables/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('plugins/datatables/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
@endpush

@push('more-scripts')
<script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/jszip.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('plugins/datatables/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/pages/datatables.init.js') }}"></script>
@endpush

@section('content')
<div class="row">
	<div class="col-12">
		<div class="card m-b-30">
			<div class="card-body">
				<h4 class="mt-0 header-title">System Settings</h4>
				<p class="sub-title">
				</p>
				<table id="datatable" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
					<thead>
						<tr>
							<th>#</th>
							<th>Name</th>
							<th>Description</th>
							<th>Value</th>
							<th>Date Created</th>
							<th>Date Updated</th>
							<th><a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown">Action </a></th>
						</tr>
					</thead>
					<tbody>
						@foreach($entities as $entity)
						<tr>
							<td>{{ $loop->iteration }}</td>
							<td>{{ ucwords(str_replace('-', ' ', $entity->name)) }}</td>
							<td>{{ $entity->description }}</td>
							<td>{{ $entity->value }}</td>
							<td>{{ date('d M, Y h:i A', strtotime($entity->created_at)) }}</td>
							<td>{{ date('d M, Y h:i A', strtotime($entity->updated_at)) }}</td>
							<td>
								<a class="btn btn-warning" href="/settings/{{ $entity->id }}/edit"><span> Edit Settings</span></a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection